# [1] 빌드 스테이지
FROM gradle:8.11.1-jdk17 AS build

WORKDIR /app

## 빌드 시 전달받은 ARG(환경변수)
#ARG JWT_SECRET
#ARG DEV_DB_HOST
#ARG RDS_PORT
#ARG DEV_DB_SCHEMA_NAME
#ARG DB_USERNAME
#ARG DEV_DB_PASSWORD
#ARG GMAIL_PWD
#ARG RIOT_API
#ARG SOCKET_SERVER_URL
#ARG FRONT_URL
#ARG PINPOINT_AGENT_ID
#ARG PINPOINT_APP_NAME

# Gradle 라이브러리 설치를 위한 초기 세팅
COPY build.gradle settings.gradle ./
RUN gradle dependencies --no-daemon

# 소스코드 복사 후 빌드
COPY . /app
RUN gradle clean build --no-daemon

# [2] 런타임 스테이지
FROM eclipse-temurin:17-jre

WORKDIR /app

# 1) 컨테이너 시간대 KST 설정
ENV TZ=Asia/Seoul
RUN apt-get update && apt-get install -y tzdata \
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo $TZ > /etc/timezone \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# 2) 빌드 결과 JAR 복사
COPY --from=build /app/build/libs/*SNAPSHOT.jar /app/gamegoov2.jar

# 3) 실행
CMD ["java",
    "-Dspring.profiles.active=dev",
    "-javaagent:/pinpoint-agent/pinpoint-bootstrap-3.0.0.jar",
    "-Dpinpoint.agentId=${PINPOINT_AGENT_ID}",
    "-Dpinpoint.applicationName=${PINPOINT_APP_NAME}",
    "-Dpinpoint.config=/pinpoint-agent/pinpoint-root.config",
    "-jar", "gamegoov2.jar"]
