spring:
  profiles:
    default: local

  # Gmail 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: gamegoo0707@gmail.com
    password: ${GMAIL_PWD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # RIOT 설정
  riot:
    api:
      key: ${RIOT_API}

springdoc:
  swagger-ui:
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    enabled: true

jwt:
  secret: ${JWT_SECRET}
  access_expiration_time: 600000 # 10분 (10 * 60 * 1000 밀리초)
  refresh_expiration_day: 14 # 2주


---
# 로컬 환경
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  datasource:
    url: jdbc:mysql://127.0.0.1:[forwardedPort]/${DB_SCHEMA_NAME}?useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

ssh:
  remote_jump_host: ${EC2_IP}
  ssh_port: 22
  user: ubuntu
  private_key: ${EC2_PRIVATE_KEY_PATH}
  database_url: ${DB_URL}
  database_port: 3306

---
# 개발 환경
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:mysql://${RDS_PRIVATE_IP}:${RDS_PORT}/${DB_SCHEMA_NAME}?useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

