name: Gamegoo Prod Deploy

on:
  push:
    branches:
      - main
      - GM9-36
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, macOS, ARM64, macmini]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create env file
        run: |
          mkdir -p ~/apps/gamegoo/env
          cat > ~/apps/gamegoo/env/.env.prod <<EOF
          SPRING_PROFILES_ACTIVE=prod
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          RDS_PRIVATE_IP=${{ secrets.RDS_PRIVATE_IP }}
          RDS_PORT=${{ secrets.RDS_PORT }}
          PROD_DB_SCHEMA_NAME=${{ secrets.PROD_DB_SCHEMA_NAME }}
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          GMAIL_PWD=${{ secrets.GMAIL_PWD }}
          RIOT_API=${{ secrets.RIOT_API }}
          DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }}
          EOF

      - name: Stop old container
        run: |
          docker rm -f gamegoo-api-v2-prod || true

      - name: Build jar
        run: |
          chmod +x ./gradlew
          ./gradlew clean bootJar

      - name: Build image
        run: |
          docker build -t gamegoo-api-v2:prod -f Dockerfile-prod .

      - name: Run container
        run: |
          docker run -d \
            --name gamegoo-api-v2-prod \
            --restart always \
            --env-file ~/apps/gamegoo/env/.env.prod \
            -p 8080:8080 \
            gamegoo-api-v2:prod

      - name: Cleanup
        run: |
          docker image prune -f
